# Generated by Django 5.2.6 on 2025-09-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('strategy', models.CharField(choices=[('ema', 'EMA Crossover'), ('sma', 'SMA Crossover'), ('rsi', 'RSI Strategy'), ('rsi_trend', 'RSI with Trend'), ('macd', 'MACD Strategy'), ('macd_zero', 'MACD Zero Cross'), ('combined', 'Combined RSI/MACD')], max_length=50, verbose_name='Стратегия')),
                ('symbol', models.CharField(max_length=10, verbose_name='Тикер')),
                ('start_date', models.DateField(verbose_name='Начальная дата')),
                ('end_date', models.DateField(verbose_name='Конечная дата')),
                ('initial_capital', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Начальный капитал')),
                ('total_return', models.FloatField(verbose_name='Общая доходность')),
                ('sharpe_ratio', models.FloatField(verbose_name='Коэффициент Шарпа')),
                ('max_drawdown', models.FloatField(verbose_name='Максимальная просадка')),
                ('win_rate', models.FloatField(verbose_name='Процент прибыльных сделок')),
                ('final_portfolio_value', models.FloatField(default=0.0, verbose_name='Конечная стоимость портфеля')),
                ('total_trades', models.IntegerField(default=0, verbose_name='Итог по сделкам')),
                ('strategy_params', models.JSONField(default=dict, verbose_name='Параметры стратегии')),
                ('equity_curve_data', models.JSONField(default=dict, verbose_name='Данные кривой доходности')),
                ('trades_data', models.JSONField(default=dict, verbose_name='Данные сделок')),
            ],
            options={
                'verbose_name': 'Результат бэктестинга',
                'verbose_name_plural': 'Результаты бэктестинга',
                'ordering': ['-created_at'],
            },
        ),
    ]
