# Generated by Django 5.2.6 on 2025-09-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestresult',
            name='avg_loss',
            field=models.FloatField(default=0.0, verbose_name='Средний убыток'),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='avg_win',
            field=models.FloatField(default=0.0, verbose_name='Средняя прибыль'),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='los_trades',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество убыточных сделок'),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='win_trades',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество прибыльных сделок'),
        ),
    ]
